#!/bin/bash

set -e

export PGPASSWORD=${POSTGRES_PASSWORD};

## Setup gophermart ##

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
  CREATE DATABASE ${POSTGRES_APP_DB};

  CREATE USER ${POSTGRES_APP_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_APP_PASS}';
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APP_DB} TO ${POSTGRES_APP_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_APP_DB}" <<-EOSQL
  GRANT ALL ON SCHEMA public TO ${POSTGRES_APP_USER};
EOSQL

## Setup accrual ##

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
  CREATE DATABASE ${ACCRUAL_DB};

  CREATE USER ${ACCRUAL_USER} WITH ENCRYPTED PASSWORD '${ACCRUAL_PASS}';
  GRANT ALL PRIVILEGES ON DATABASE ${ACCRUAL_DB} TO ${ACCRUAL_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${ACCRUAL_DB}" <<-EOSQL
  GRANT ALL ON SCHEMA public TO ${ACCRUAL_USER};
EOSQL